title: "link-bridge"
description: "Secure file upload & AI chat"
baseurl: "/link-bridge"
url: "https://sumdaniweb-ux.github.io"
theme: null
markdown: kramdown
plugins:
  - jekyll-seo-tag
exclude: [README.md, LICENSE]
